name: CI Security & Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    name: Lint, Security Scan, Build & Docker
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4️⃣ Fix known vulnerabilities
      - name: Fix known vulnerabilities
        run: npm audit fix || echo "Audit fix completed"

      # 5️⃣ Run ESLint
      - name: Run Linter
        run: npx eslint src --max-warnings=0

      # 6️⃣ Secret Detection
      - name: Detect secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

      # 7️⃣ Trivy File System Scan (fail for HIGH or CRITICAL)
      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          format: table
        env:
          TRIVY_DISABLE_VEX_NOTICE: true

      # 8️⃣ Build React app
      - name: Build React app
        run: npm run build

      # 9️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔟 Build Docker Image
      - name: Build Docker image
        run: docker build -t reactapp:latest .

      # 1️⃣1️⃣ Trivy Image Scan (fail for HIGH or CRITICAL)
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: reactapp:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          format: table
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
